const products = [
    
    {
      id: 2,
      image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/l/r/w/-original-imagj5wzxrfpye64.jpeg?q=70",
      name: "Analog Watch - For Men NJ0154-80H",
      originalPrice: 34000,
      discountedPrice: '',
      on_sells: true,
    },
    {
      id: 3,
      image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/h/m/w/1-dw00100631-daniel-wellington-men-original-imags9wbby9tyrzt.jpeg?q=70",
      name: "Classic Evergold Black color Round - 40 mm diameter Analog Watch - For Men DW00100631",
      originalPrice: 8400,
      discountedPrice: '',
      on_sells: true,
    },
    {
        id: 4,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/v/1/l/-original-imagzn92eza5zk6h.jpeg?q=70",
        name: "Enticer Men Analog Watch - For Men A2228 (MTP-1375D-2A1VDF)",
        originalPrice: 5300,
        discountedPrice: '',
        on_sells: true,
      },
      {
        id: 5,
        image: "https://rukminim2.flixcart.com/image/612/612/kn4xhu80/watch/s/o/o/dtwgf2019202-ducati-corse-original-imagfvmry3cdyn4f.jpeg?q=70",
        name: "Classic Chrono Analog Watch - For Men DTWGF2019202",
        originalPrice: 11000,
        discountedPrice: '',
        on_sells: true,
      },
      {
      id: 1,
      image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/b/v/d/-original-imagsykxadjqu9ge.jpeg?q=70",
      name: "Enticer Men Analog Watch - For Men A1856 (MTP-VD300G-1EUDF)",
      originalPrice: 6700,
      discountedPrice: '',
      on_sells: true, 
    },
    {
        id: 6,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/q/8/9/1-fca05-5-french-connection-men-original-imah4j35h3rbujer.jpeg?q=70",
        name: "Automatic Black Dial Analog Watch - For Men FCA05-5",
        originalPrice: 8000,
        discountedPrice: '',
        on_sells: true, 
      },
      {
        id: 7,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/s/w/8/-original-imagsykxraxeqgcf.jpeg?q=70",
        name: "Hampton Analog Watch - For Men AX2122",
        originalPrice: 7400,
        discountedPrice: '',
        on_sells: true, 
      },
      {
        id: 8,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/r/2/4/-original-imagpfdv7q3cg7cn.jpeg?q=70",
        name: "Edifice EFR-539BK-1AVUDF Black Dial Black Stainless Steel Band Analog Watch - For Men EX187",
        originalPrice: 13995,
        discountedPrice: '',
        on_sells: true, 
      },
      {
        id: 9,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/j/m/a/-original-imagpfdvuggqrws2.jpeg?q=70",
        name: "MAX Analog Watch - For Men TH1791973",
        originalPrice: 14250,
        discountedPrice: '',
        on_sells: true, 
      },
      {
        id: 10,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/p/d/y/-original-imagzegmbynhyhpg.jpeg?q=70",
        name: "Analog Watch - For Men W0668G3",
        originalPrice: 7019,
        discountedPrice: '',
        on_sells: true, 
      },
      {
        id: 11,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/l/i/j/-original-imagptvypzm35hba.jpeg?q=70",
        name: "Luther Analog Watch - For Men BQ2328",
        originalPrice: 8600,
        discountedPrice: 9500,
        discounted: true, 
      },
      {
        id: 12,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/7/p/n/-original-imah6b6hn8fjrj85.jpeg?q=70",
        name: "Automatic Silver Dial Analog Watch - For Men TWEG208SMU08",
        originalPrice: 5000,
        discountedPrice: 6000,
        discounted: true, 
      },
      {
        id: 13,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/u/1/z/-original-imah7eayxkmjsdkz.jpeg?q=70",
        name: "Automatic Black Dial Analog Watch - For Men TW000Z801",
        originalPrice: 6500,
        discountedPrice: 7500,
        discounted: true, 
      },
      {
        id: 14,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/i/k/h/-original-imagzj6gwvzhg8w3.jpeg?q=70",
        name: "Regalia Maritime Analog Watch - For Men NQ1830KM01",
        originalPrice: 10500,
        discountedPrice: 12000,
        discounted: true, 
      },
      {
        id: 15,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/d/f/a/-original-imagzhjtncxxvcgm.jpeg?q=70",
        name: "Octane upgrade Analog Watch - For Men NP90086SM01",
        originalPrice: 12500,
        discountedPrice: 15000,
        discounted: true, 
      },
      {
        id: 16,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/q/b/s/-original-imagptvyhwxryycv.jpeg?q=70",
        name: "Bannon Analog Watch - For Men BQ2491",
        originalPrice: 12000,
        discountedPrice: 14000,
        discounted: true, 
      },
      {
        id: 17,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/s/a/n/-original-imagswy4exbdxqzz.jpeg?q=70",
        name: "Analog Watch - For Men AX1870",
        originalPrice: 8000,
        discountedPrice: 10000,
        discounted: true, 
      },
      {
        id: 18,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/m/m/p/1-sb-1-10608-3-santa-barbara-polo-racquet-club-men-original-imah7uu3uzrkaayw.jpeg?q=70",
        name: "Quartz Blue Dial Analog Watch - For Men SB.1.10608-3",
        originalPrice: 16000,
        discountedPrice: 19000,
        discounted: true, 
      },
      {
        id: 19,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/5/p/i/1-bp5023y-130-beverly-hills-polo-club-men-original-imah5uqwbwjz6ebf.jpeg?q=70",
        name: "Beverly Hills Polo Club Multi Function Analog Watch - For Men BP5023Y.130",
        originalPrice: 18000,
        discountedPrice: 20000,
        discounted: true, 
      },
      {
        id: 20,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/a/v/d/1-sb-1-10608-2-santa-barbara-polo-racquet-club-men-original-imah7uu3tvfryv7g.jpeg?q=70",
        name: "Quartz Black Dial Analog Watch - For Men SB.1.10608-2",
        originalPrice: 16000,
        discountedPrice: 18000,
        discounted: true, 
      },
  ];
  
  export default products;